---
title: "A quantitative approach to evaluating the GWP timescale through implicit discount rates"
journal: "`r rticles::copernicus_journal_abbreviations(journal_name = 'communication')`"
author:
  - given_name: 
    surname: 
    affiliation:
abstract: |
running:
  title: "INSYDE"
  author: "Dottori"
output:
  rticles::copernicus_article: default
---

# Introduction

The global warming potential (GWP) is the primary metric used to assess the equivalency of emissions of different greenhouse gases (GHGs).
This primacy was established soon after its development in 1990 due to its early use by the WMO (1992) and UNFCCC (1995). 
However, despite the political acceptance, the GWP has also been a source of controversy and criticism:
that radiative forcing as a measure of impact is not as relevant as temperature or damages; 
that the assumption of constant future GHG concentrations is unrealistic; 
that discounting is preferred to a constant time period of integration; 
disagreements about the choice of time horizon in the absence of discounting; 
that dynamic approaches would lead to a more optimal resource allocation over time;
that the GWP does not account for non-climatic effects such as carbon fertilization or ozone produced by methane;
and that pulses of emissions are less relevant than streams of emissions.
Including these complicating factors would make the metric less simple and transparent and would require reaching a consensus regarding appropriate parameter values and model choices.
The simplicity of the calculation of the GWP is one of the reasons for its widespread use.
In this paper, we focus on the choice of time horizon in the GWP that can reflect decision-maker values, but for which additional clarity regarding the implications of the time horizon could be useful. 
We also investigate the extent to which the choice of time horizon can incorporate many of the complexities of assessing the impacts described in the previous paragraph. 
The 100-year time horizon of the GWP (GWP100) is the time horizon most commonly used in many venues, for example in the Kyoto Protocol, perhaps because it was the middle value of the three time horizons (20, 100, and 500 years) analyzed in the IPCC First Assessment Report.
However, the 100-year time horizon has been described by some as arbitrary. 
The IPCC AR5 stated that “[t]here is no scientific argument for selecting 100 years compared with other choices”. 
The WMO (1992) assessment has provided a justifications for the 100-year time horizon, stating that “the GWPs evaluated over the 100-year period appear generally to provide a balanced representation of the various time horizons for climate response”. 
Recently, some researchers and NGOs have been promoting more emphasis on shorter time horizons, such as 20 years, which would highlight the role of short-lived climate forcers such as CH\textsubscript{4}. 
These studies each have different nuances regarding their recommendations – for example, pairing the GWP100 with the GWP20 to reflect both long-term and near-term climate impacts. 
It is plausible that more consideration of short-term metrics would result in policy that weights near-term impacts more heavily. 
In contrast, some governments have suggested the use of the 100-year global temperature change potential (GTP) based on the greater physical relevance of temperature in comparison to forcing, in effect downplaying the role of the same short-lived climate forcer. 
Therefore, the question of timescale remains an area of active debate. 
We argue that more focus on quantitative justifications for timescales within the GWP structure would be of value, as differentiated from qualitative justifications such as a need for urgency to avoid tipping points.
This paper provides a needed quantification and analysis of the implications of different GWP time horizons. 
We follow the lead of economists who have proposed that the appropriate comparison for different options for GHG emissions policies is between the net present discounted marginal damages. 
This paper reframes and clarifies key issues and presents a framework for better understanding how different timescales can be reconciled with how the future is valued. 
The paper focuses on CO\textsubscript{2} and CH\textsubscript{4} as the two most important anthropogenic contributors to current warming, but the methodology is applicable to emissions of other gases, and sensitivity analyses consider N\textsubscript{2}O.

# Methods 

The general approach taken in this paper is to calculate the impact of a pulse of emissions of either CO\textsubscript{2} or CH\textsubscript{4} in the first year of simulation on a series of climatic variables. 
The first step is to calculate the perturbation of atmospheric concentrations over a baseline scenario. 
The concentration perturbation is transformed into a change in the global radiative forcing balance. 
The radiative forcing perturbation over time is used to calculate the impact on temperature and then damages due to that temperature change. 
Discount rates are then applied to these impacts to determine the net present value of the impacts. 
The details of these calculations are described here.

__Concentration:__ The perturbation due to a pulse of CO\textsubscript{2} is determined by the use of IPCC AR5 equations (see Table 8.SM.10 from the IPCC AR5 assessment). The perturbation due to a pulse of CH\textsubscript{4} is calculated by the use of a 12.4-year lifetime, consistent with Table 8.A.1 from IPCC AR5. In this paper, a pulse of 28.3 Mt of CH\textsubscript{4} is used (sufficient for a 10 ppb change in global CH\textsubscript{4} concentrations in the pulse year; results of a larger pulse are described in Sect. 3.3). The mass of the gas is converted to concentrations by assuming a molecular weight of air of 29 g mole−1 and a mass of the atmosphere of 5.13×1018 kg. These perturbations are added to baseline concentration pathways; for this study, we use the four RCP scenarios based on data from http://www.pik-potsdam.de/~mmalte/rcps/ (last access: 14 August 2018). This approach parallels the standard IPCC approach; however, various papers have noted that the lifetime of CO\textsubscript{2} presented in the IPCC includes climate carbon feedbacks, whereas the lifetime of CH\textsubscript{4} does not, which is a potential inconsistency (Gasser et al., 2017; Sterner and Johansson, 2017). The discussion in Sect. 3.3 and 3.4 elaborates on the consequences of these choices.

# Results 

## Evaluating the climate effects of an emission pulse of CH\textsubscript{4}

The analysis starts by calculating the climate effects of an emission pulse of CH4. 
We introduce an emission pulse of 28.3MT in 2011 (yielding a 10 ppb increase in CH4 concentration in the initial year) applied on top of the GHG concentrations of Representative Concentration Pathway (RCP) 6.0. 
Figure 1 shows the changes in radiative forcing (RF; a), temperature (T; b), damages (c), and damages discounted at a 3% rate (d) out to the year 2300 resulting from such a pulse. 
Figure 1 relies on calculations that use central estimates of the uncertain parameters, as discussed in the Methods section. 
While the graph is truncated at 2300, the calculations used in this paper extend to 2500. 
The impacts of an emission pulse of CO2 are also shown using 24.8 times the mass of the CH4 pulse (this factor is chosen to create equivalent integrated damages over the full time period when discounted at 3% as shown in Fig. 1d). 
Figure 1a and b demonstrate the trade-offs between near- term and long-term impacts when assigning equivalency to emission pulses of different lifetimes. 
After 100 years, the radiative forcing effects of the CH4 pulse decay to 0.04% of the initial forcing in the year of the emission pulse, and the temperature effects decay to 4% of the peak temperature (reached 10 years after the pulse). 
In contrast, after 100 years the radiative forcing effects of the CO2 pulse decay to 22% of the initial forcing, and the temperature effects decay to 51% of the CO2 peak temperature (reached 18 years after the pulse). 
The immediacy of the temperature effects for the CH4 pulse creates larger damages in both overall and discounted dollar terms for the first 42 years. 
After 43 years, the sustained CO2 effects overtake the CH4 effects.
With a different discount rate, a different factor would have been used to calculate the CO2 mass used for the CO2 pulse, which would change the crossing point for damages – a higher discount rate would require a larger CO2 equivalent pulse relative to the CH4 pulse and therefore an earlier crossing point (and vice versa). 
Figure 1c demonstrates the dramatic increase in damage over time due to the relationship of damage to economic growth. 
In the case of CH4, damage peaks in 2032 and declines until 2080 as a result of the short lifetime of the gas. 
The increase in damages after 2080 is due to the component of the temperature response function that includes a 409-year timescale decay rate such that after 100 years the decrease in the DELTAT2 component of the damage equation is about 0.5%/year, and because that decay rate is slower than the rate of GDP growth, net damages grow. 
Figure 1d demonstrates the dramatic decrease in future damages when applying a constant discount rate. 
Taken as a whole, these four figures demonstrate the trade-offs required when attempting to create equivalences for emissions of gases with very different lifetimes.

## Sensitivity analysis

Figure 2 shows the median, interquartile, interdecile, and extremes of the equivalent GWP time horizon corresponding to a given discount rate from a sensitivity analysis. 
The uncertainty was calculated assuming equal likelihood of each of the 972 combinations of all of the parameter choices used in this paper: 
four RCPs, three climate sensitivities, three damage exponents, three forcing imbalance options, three temperature offsets, and three GDP growth rates. 
The ranges chosen for each parameter are described in the Methods section. 
The parameters with the largest effect on the uncertainty of the calculated GWP (at a discount rate of 3 %) are the rate of GDP growth and the damage exponent (see Table 1). 
For these six parameters, the choices that lead to larger damages from CH4 relative to CO2 are a low GDP growth, a low damage exponent, a low-emissions scenario, a higher temperature offset (e.g., assuming that damages are a function of warming from preindustrial, not warming from present day), a lower climate sensitivity, and a higher current forcing imbalance. 
The general trend is that the more that damages are expected to grow in the future (e.g., high GDP growth, damage exponent, or emissions scenario), the longer the equivalent timescale is for a given discount rate. 
While CO2 and CH4 are the largest contributors to climate change (as evaluated by contributions of historical emissions to present-day radiative forcing as in Table 8.SM.6 in the IPCC and by the magnitude of present-day emissions as evaluated by the standard GWP100), it is also informative to evaluate emissions of other gases with these techniques. 
Table 2 shows five gases and their atmospheric lifetimes. 
For each gas, an “optimal” GWP timescale was calculated that would replicate the ratio of net present damage of that gas to CO2 at a discount rate of 3 %. 
The ratio of the GWP100 and the GWP20 to that optimal damage ratio is also shown. 
For longer-lived gases (e.g., N2O and HFC-23), there is no integration time period that can produce a ratio as large as the calculated damage ratio at a discount rate of 3 %. 
For these gases, we list the timescale that yields the maximum possible ratio and note that the GWP for longer-lived gases is fairly insensitive to timescale (further comparisons of non-CO2 gases are presented in the Supplement). 
This table shows that at a discount rate of 3% and as evaluated using net present damage ratios, the use of a 100-year timescale is consistent (interquartile range) with the optimal timescale / damage ratios for methane. 
For gases with lifetimes in centuries, the GWP at any timescale undervalues these gases, but the magnitude of that undervaluation is somewhat insensitive to the choice of timescale. 
For the longest-lived gases, the GWP also undervalues reductions in these gases, but the longer the timescale the better the match.



